CREATE TABLE `TCC_TRANSACTION` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '服务端自增ID',
  `DOMAIN` varchar(100) DEFAULT NULL COMMENT '',
  `GLOBAL_TX_ID` varbinary(32) NOT NULL COMMENT '全局事务ID',
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL COMMENT '分支限定符',
  `CONTENT` varbinary(8000) DEFAULT NULL COMMENT '附加内容',
  `STATUS` int(11) DEFAULT NULL COMMENT '事务状态',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL COMMENT '事务类型',
  `RETRIED_COUNT` int(11) DEFAULT NULL COMMENT '重试次数',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `VERSION` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '分布式事务TCC';